---
title: "Keana Richards's CV"
author: Keana Richards
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---
```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "data/",  
  pdf_mode = params$pdf_mode
)

```

```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```

Aside
================================================================================

--------------------------------------------------------------------------------

```{r}
CV %<>% print_contact_info()
```

Statistical Software {#skills}
--------------------------------------------------------------------------------

- R
- SPSS
- Python 

```{r}
## CV %<>% print_skill_bars()
```

Statistical areas of expertise {#analysis}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_text_block('data_analysis')
```

Research strengths {#visualization}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_text_block('research')
```


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R packages [**pagedown**](https://github.com/rstudio/pagedown) and [***datadrivencv***](https://github.com/nstrayer/datadrivencv). 

The source code is available [on github.com/keanarichards/resume](https://github.com/keanarichards/resume).

Last updated on `r Sys.Date()`.

Main
================================================================================

Keana Richards {#title}
--------------------------------------------------------------------------------

Relevant Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('experience')

```

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


